prompts = [
    "Chest X-ray showing Pneumonia",
    "Chest X-ray showing Pulmonary edema",
    "Chest X-ray showing Pleural effusion",
    "Chest X-ray showing Pneumothorax",
    "Chest X-ray showing Hemothorax",
    "Chest X-ray showing Pulmonary embolism",
    "Chest X-ray showing Chronic obstructive pulmonary disease (COPD)",
    "Chest X-ray showing Emphysema",
    "Chest X-ray showing Bronchiectasis",
    "Chest X-ray showing Interstitial lung disease",
    "Chest X-ray showing Pulmonary fibrosis",
    "Chest X-ray showing Tuberculosis",
    "Chest X-ray showing Lung cancer",
    "Chest X-ray showing Pulmonary nodules",
    "Chest X-ray showing Atelectasis",
    "Chest X-ray showing Sarcoidosis",
    "Chest X-ray showing Asbestosis",
    "Chest X-ray showing Silicosis",
    "Chest X-ray showing Miliary tuberculosis",
    "Chest X-ray showing Pulmonary hypertension",
    "Chest X-ray showing Mediastinal mass",
    "Chest X-ray showing Hilar lymphadenopathy",
    "Chest X-ray showing Pneumomediastinum",
    "Chest X-ray showing Pneumopericardium",
    "Chest X-ray showing Foreign body aspiration",
    "Chest X-ray showing Cardiomegaly",
    "Chest X-ray showing Congestive heart failure",
    "Chest X-ray showing Pericardial effusion",
    "Chest X-ray showing Aortic aneurysm",
    "Chest X-ray showing Aortic dissection",
    "Chest X-ray showing Pulmonary artery enlargement",
    "Chest X-ray showing Calcified heart valves",
    "Chest X-ray showing Ventricular septal defect",
    "Chest X-ray showing Atrial septal defect",
    "Chest X-ray showing Coarctation of the aorta",
    "X-ray showing Bone fracture",
    "X-ray showing Dislocation",
    "X-ray showing Osteoarthritis",
    "X-ray showing Rheumatoid arthritis",
    "X-ray showing Osteoporosis",
    "X-ray showing Bone tumor",
    "X-ray showing Osteomyelitis",
    "X-ray showing Paget's disease",
    "X-ray showing Scoliosis",
    "X-ray showing Kyphosis",
    "X-ray showing Spinal compression fractures",
    "X-ray showing Spondylolisthesis",
    "X-ray showing Spondylosis",
    "X-ray showing Ankylosing spondylitis",
    "X-ray showing Metastatic bone disease",
    "X-ray showing Cervical spine fractures",
    "X-ray showing Lumbar spine fractures",
    "X-ray showing Degenerative disc disease",
    "X-ray showing Herniated disc",
    "X-ray showing Spinal stenosis",
    "X-ray showing Skull fractures",
    "X-ray showing Craniosynostosis",
    "X-ray showing Hydrocephalus",
    "X-ray showing Sinusitis",
    "X-ray showing Mastoiditis",
    "X-ray showing Dental caries",
    "X-ray showing Periodontal disease",
    "X-ray showing Impacted teeth",
    "X-ray showing Jaw fractures",
    "X-ray showing Temporomandibular joint disorder",
    "X-ray showing Maxillary sinusitis",
    "X-ray showing Mandibular cysts",
    "X-ray showing Osteonecrosis of the jaw",
    "Abdominal X-ray showing Bowel obstruction",
    "Abdominal X-ray showing Ileus",
    "Abdominal X-ray showing Perforated viscus",
    "Abdominal X-ray showing Pneumoperitoneum",
    "Abdominal X-ray showing Renal calculi",
    "Abdominal X-ray showing Ureteral calculi",
    "Abdominal X-ray showing Bladder stones",
    "Abdominal X-ray showing Gallstones",
    "Abdominal X-ray showing Ascites",
    "Abdominal X-ray showing Hepatomegaly",
    "Abdominal X-ray showing Splenomegaly",
    "Abdominal X-ray showing Abdominal aortic aneurysm",
    "Abdominal X-ray showing Calcified lymph nodes",
    "Abdominal X-ray showing Foreign bodies",
    "Abdominal X-ray showing Intra-abdominal masses",
    "Pediatric X-ray showing Developmental dysplasia of the hip",
    "Pediatric X-ray showing Slipped capital femoral epiphysis",
    "Pediatric X-ray showing Legg-Calvé-Perthes disease",
    "Pediatric X-ray showing Osgood-Schlatter disease",
    "Pediatric X-ray showing Greenstick fractures",
    "Pediatric X-ray showing Growth plate fractures",
    "Pediatric X-ray showing Congenital scoliosis",
    "Pediatric X-ray showing Bronchiolitis",
    "Pediatric X-ray showing Foreign body ingestion",
    "Pediatric X-ray showing Meconium ileus",
    "Pediatric X-ray showing Necrotizing enterocolitis",
    "X-ray showing Soft tissue emphysema",
    "X-ray showing Calcified granulomas",
    "X-ray showing Foreign bodies",
    "X-ray showing Medical device placement",
    "X-ray showing Pneumatosis intestinalis",
    "X-ray showing Cholelithiasis",
    "X-ray showing Bladder diverticula",
    "X-ray showing Uterine fibroids",
    "X-ray showing Prostatic calcifications",
    "X-ray showing Breast calcifications",
    "X-ray showing Mammographic findings"
]